### ISSUE TITLE
StreamWithSend.send throw java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by DragonLi** [SodiumFRP/sodium#74]
When I run the example code dynamic.java under book/zombicus directroy, the program throws the following exception randomly:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at sodium.StreamWithSend.send(StreamWithSend.java:20)
	at sodium.Cell$13$1ApplyHandler$1.run(Cell.java:313)
	at sodium.Cell$13$1ApplyHandler$1.run(Cell.java:1)
	at sodium.Transaction.close(Transaction.java:251)
	at sodium.Transaction.run(Transaction.java:129)
	at sodium.StreamSink.send(StreamSink.java:42)
	at Animate.animate(Animate.java:120)
	at dynamic.main(dynamic.java:159)

another running may throw with similar stack traces:
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at sodium.StreamWithSend.send(StreamWithSend.java:20)
	at sodium.Stream$12.run(Stream.java:282)
	at sodium.StreamWithSend$2.run(StreamWithSend.java:29)
	at sodium.StreamWithSend$2.run(StreamWithSend.java:1)
	at sodium.Transaction.close(Transaction.java:251)
	at sodium.Transaction.run(Transaction.java:129)
	at sodium.StreamSink.send(StreamSink.java:42)
	at Animate.animate(Animate.java:120)
	at dynamic.main(dynamic.java:159)

the relevant code of StreamWithSend is:

      HashSet<Node.Target> listeners;
        synchronized (Transaction.listenersLock) {
            listeners = new HashSet<Node.Target>(node.listeners);
        }
		for (final Node.Target target : node.listeners) {
            trans.prioritized(target.node, new Handler<Transaction>() {
                public void run(Transaction trans2) {
                    Transaction.inCallback++;
                    try {  // Don't allow transactions to interfere with Sodium
                           // internals.
                        // Dereference the weak reference
//                        TransactionHandler<Unit> uta = target.action.get();
//                        if (uta != null)  // If it hasn't been gc'ed..., call it
//                            ((TransactionHandler<A>)uta).run(trans2, a);
                        @SuppressWarnings("unchecked")
						TransactionHandler<A> uta = (TransactionHandler<A>)target.action.get();
                        if (uta != null)  // If it hasn't been gc'ed..., call it
                            uta.run(trans2, a);
                    } catch (Throwable t) {
                        t.printStackTrace();
                    }
                    finally {
                        Transaction.inCallback--;
                    }
                }
            });

it seems that the loop should use the copy listeners instead of node.listeners, but I don't understand the inter working of sodium, so I am not sure about it. I modify my local code and it seems the problem disappear.

**Comment by the-real-blackh** [comment]
Oops. I spotted my mistake and fixed it. Try now.
